### library load:
library(readxl)
library(tidyverse)
library(lubridate)
library(sf)
library(terra)
#install.packages("readxl")
getwd()
#install.packages("tidyverse")
#install.packages("lubridate")
#install.packages("sf")
#install.packages("terra")
